import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../public/js/app.js',import.meta.url),'utf8');
const api=fs.readFileSync(new URL('../functions/api/[[path]].js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../public/service-worker.js',import.meta.url),'utf8');
const nav=(html.match(/<nav class="bottom-nav">[\s\S]*?<\/nav>/)||[''])[0];
assert.equal((nav.match(/<button class="nav/g)||[]).length,6,'bottom nav must have 6 buttons');
assert.match(html,/data-page="more"/);
assert.doesNotMatch(html,/id="productCategory"/);
assert.doesNotMatch(html,/xlsx\.full\.min\.js"><\/script>/);
assert.doesNotMatch(html,/tesseract\.min\.js"><\/script>/);
assert.match(js,/ensureXLSX/);assert.match(js,/ensureTesseract/);
assert.match(js,/showCustomerRename/);assert.match(js,/showSaleEdit/);assert.match(js,/showStockinEdit/);
assert.match(api,/case "sale\.update"/);assert.match(api,/case "stockin\.update"/);assert.match(api,/case "data\.tabular\.import"/);
assert.match(api,/function validateAIPlan/);assert.match(api,/store\.snapshots\.length>12/);
assert.match(html,/CANTIN AI NEXT 4\.12/);assert.match(sw,/v4-12/);
console.log('PASS v4.12 static UI/build assertions');
